### ISSUE TITLE
When will ChartSFT be released?

### ISSUE THREAD

**Issue by nemonameless** [OpenGVLab/ChartAst#1]
Nice work, when will ChartSFT be released? Thanks

**Comment by FanqingM** [comment]
This work is under review, It will be released when it have results.  Thank you for your approva

**Comment by HAWLYQ** [comment]
Great work! Could you please consider releasing ChartSFT earlier?  This will help me a lot!

**Comment by FanqingM** [comment]
We would consider it. Thank you for your approval

> Great work! Could you please consider releasing ChartSFT earlier? This will help me a lot!

**Comment by BuaaAlban** [comment]
> We would consider it. Thank you for your approval
> 
> > Great work! Could you please consider releasing ChartSFT earlier? This will help me a lot!

Millions of people are looking forward for your release!

**Comment by FanqingM** [comment]
We are considering releasing ChartSFT after the article has been reviewed. However, if you have an urgent need, you can contact Fanqing Meng at [mengfanqng33@gmail.com]

**Comment by nemonameless** [comment]
hope to release this sft dataset, thanks
