### ISSUE TITLE
Asking for DATA～

### ISSUE THREAD

**Issue by Cuiunbo** [OpenGVLab/ChartAst#12]
Hi! This work is great. May I ask when you can open source your SFT data? Your SFT data seems to be of very high quality, and we hope to be able to use it in our work.

**Comment by nemonameless** [comment]
https://github.com/OpenGVLab/ChartAst/issues/1

**Comment by FanqingM** [comment]
We have released the ChartSFT in https://huggingface.co/datasets/FanqingM/ChartAssistant 🔥🔥🔥
