### ISSUE TITLE
About the Chart-Table Pretrain Data

### ISSUE THREAD

**Issue by Coobiw** [OpenGVLab/ChartAst#13]
Hello, thanks for your great work! I'm curious about the re-plot ops of ChartQA and PlotQA to do chart-table-alignment pretrain stage. In my knowledge, PlotQA Dataset doesn't have the .csv file. So how do you get the table data? Looking forward to your reply!

**Comment by FanqingM** [comment]
Actually, plotQA and ChartQA all have their corrsponding tables, we use differenct API to re-plot them, and add arxiv table-chart pairs in chart-table-alignment pretrain stage.
for plotqa(https://github.com/NiteshMethani/PlotQA/blob/master/PlotQA_Dataset.md), you should write code to extract table from annotations.

**Comment by Coobiw** [comment]
Thanks, I've done this!
