### ISSUE TITLE
Inquiry about the Possibility of Sharing Generated Code Dataset Publicly

### ISSUE THREAD

**Issue by buckerF** [OpenGVLab/ChartAst#17]
Hello,

I hope this message finds you well. I am reaching out to inquire about the possibility of publicly sharing a dataset consisting of generated code.

Could you please provide guidance on whether it is permissible to share such a dataset publicly? Additionally, are there any specific considerations or requirements that I should be aware of when sharing code datasets?

Thank you for your assistance.

Best regards,

**Comment by FanqingM** [comment]
Hi, sorry but I do not unerstand what you mean?
We already release the dataset. If you need the code to generate it?

**Comment by Zxmw** [comment]
I have a similar problem. I would like to check if the uploaded dataset contains style-augmented charts and charts with specialized types, as mentioned in the paper. Thank you!

**Comment by Zxmw** [comment]
I have a similar quetion. I would like to check if the uploaded dataset contains style-augmented charts and charts with specialized types, as mentioned in the paper. Thank you!

**Comment by FanqingM** [comment]
> I have a similar quetion. I would like to check if the uploaded dataset contains style-augmented charts and charts with specialized types, as mentioned in the paper. Thank you!

Hi, We release the MathQA,ReferQA, and arxiv dataset, which is the main contribution of ChartSFT.
For Chart-to-Table, we will release it in this week.

**Comment by Zxmw** [comment]
> > I have a similar quetion. I would like to check if the uploaded dataset contains style-augmented charts and charts with specialized types, as mentioned in the paper. Thank you!
> 
> Hi, We release the MathQA,ReferQA, and arxiv dataset, which is the main contribution of ChartSFT. For Chart-to-Table, we will release it in this week.

I see, thanks for the quick reply. It helped me a lot.
