### ISSUE TITLE
Got killed at initializing meta model

### ISSUE THREAD

**Issue by yanchuqiao** [OpenGVLab/ChartAst#18]
Hi, thank you for sharing your work. I am using single_turn_eval.py to do chart summarization tasks. But my model keeps got killed at initializing the model ' model = MetaModel(args.llama_type, args.llama_config, args.tokenizer_path, with_visual=True)'. My GPU has 64GB Ram. Would it be possible to change to a smaller model? Can you give some hints? 

Thank you

**Comment by FanqingM** [comment]
Do you use the right llama_type? (llama_ens5)
I use only one A100(80G) to do the inference

**Comment by FanqingM** [comment]
You can use http://106.14.127.192:7861/ to do some tests?
We deploy a demo in it
