### ISSUE TITLE
Will there be an online demo?

### ISSUE THREAD

**Issue by wenyihong** [OpenGVLab/ChartAst#2]
Will there be an online demo? Thanks!

**Comment by FanqingM** [comment]
Yes, we will open the model weight next week, thank you for your approval

**Comment by FanqingM** [comment]
We also plan to deploy an online demo for easy access, which is likely to be completed this month. However, the model weights will be released very soon. These model weights have undergone testing and have shown strong zero-shot capabilities in tasks such as ChartQA, MathQA, ReferQA, and OCR.

**Comment by FanqingM** [comment]
https://pan.baidu.com/s/1t0QPLDfULNovnYKtsQxjOQ password: 10el
The model weight has been realeased

**Comment by FanqingM** [comment]
http://106.14.127.192:7861/
Hi, How about use it?

**Comment by ghost-909** [comment]
> http://106.14.127.192:7861/ Hi, How about use it?

网址打不开
