### ISSUE TITLE
Questions about the training details about ChartAst-S

### ISSUE THREAD

**Issue by zengxingchen** [OpenGVLab/ChartAst#7]
Thanks for your excellent work! 
After carefully reading the paper, I still have questions about the trainable setting of ChartAst-S. 
Which part of the model is trainable/frozen in pertaining and instruction tuning stages, respectively? Vision tower, projection layer, and LLM? 

Thx again.

**Comment by FanqingM** [comment]
Same with [SPHINX](https://github.com/Alpha-VLLM/LLaMA2-Accessory), We train the projection, part of vision encoders and part of LLM (llama2)
