### ISSUE TITLE
Questions about Installation / Use

### ISSUE THREAD

**Issue by whishei** [OpenGVLab/ChartAst#9]
I am looking to test ChartAssistant on a certain type of graph my research group is interested in, but I am having trouble installing your model. Some questions:

- Do you need GPUs to use your model?
- Can you provide any help with installing to test on a Mac or on Google Colab if a GPU is needed. 

I have downloaded the consolidated models from HuggingFace and (hopefully correctly) went through the set-up process for LLaMA2-Accessory.

**Comment by FanqingM** [comment]
Hello, thank you for your appreciation!
First, I use one A100 80G to do inference, the script is in accessory/exps/finetune/mm/test.sh (you can also use single_turn_eval.py).
Second, for the neccessary environment, it is same with SPHINX which in is the readme.

Is there some trouble to run this scipt? Please let me know

**Comment by whishei** [comment]
Thank you! I was having trouble running the script with line: 

"srun -p Gveval-P1 --gres=gpu:1 --job-name=sam_bf_Chart_debug --cpus-per-task 12 -n1 --ntasks-per-node=1  --quotatype=auto python -u accessory/single_turn_eval_multitask.py \,"
on both my Mac and Google Colab specifically with the error of:
"srun: not found"
Probably because I am not running on Linux or an HPC environment. 

Instead I am just trying python single_turn_eval_multitask.py on Colab. I will update if I have further issues thank you. 

I was also wondering if you have any tips / instructions for fine-tuning your model for chart-to-table: 
-how to prepare the training data (image formatting: png/jpeg/etc. and table formatting)
-estimation of amount of training data needed? 

This is my first time attempting to fine-tune such a large model, so any help would be appreciated, thank you!
